### ISSUE TITLE
ResourceNotFound: open_ptrack_yolo_detector

### ISSUE THREAD

**Issue by dagelabi** [OpenPTrack/open_ptrack_v2#10]
Hi,

After doing the calibration, when I launch the dectection line :  `roslaunch detection detection_node_(sensor_name).launch`

I get the error : 
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 748, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 720, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 654, in _recurse_load
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 684, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 588, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: open_ptrack_yolo_detector
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/user/workspace/ros/src
ROS path [2]=/opt/ros/kinetic/share
```

From what I understand, it could not find `detector_yolo_zed.launch` in my dection node launch file (line 16) because et cannot find `$(find open_ptrack_yolo_detector)`

If I replace
`<include file="$(find open_ptrack_yolo_detector)/launch/detector_yolo_zed.launch"`
by
`<include file="/home/user/workspace/ros/src/open_ptrack/yolo_detector/launch/detector_yolo_zed.launch">`

On each node, I get no error, but the Master node keep displaying : 
[ WARN]: [/zed_camera_1] still waiting for detection messages...
[ WARN]: [/zed_suivi] still waiting for detection messages...

**Comment by dagelabi** [comment]
Well, it might not be related to openPTrack itself, but each time there's an <arg> tag in a launch file, it uses the default value even if the arg is provided

**Comment by marketto89** [comment]
@dagelabi,

the commit 2eb95e1 should fix the issue you had.

Let us know if that's the case!

**Comment by dagelabi** [comment]
@marketto89, 

The commit fixed the the ResourceNotFound error. :smile: 

However, when I start the tracking, the Master node keep displaying :
[ WARN]: [/zed_camera_1] still waiting for detection messages...
[ WARN]: [/zed_suivi] still waiting for detection messages...

and this message in loop ( one for each node connected )
[ERROR] [1516651703.903700369]: transform exception: Could not find a connection between 'world' and 'camera_1_depth_frame' because they are not part of the same tree.Tf has two or more unconnected trees. If you are seeing just one error like this do not worry, I am probably working

I tried going through the calibration process again, but I get the same error. Should I start another issue ? 
Thanks !

**Comment by marketto89** [comment]
Hey @dagelabi 

it seems OpenPTrack does not find the network calibration information. Did you follow the [network calibration procedure](https://github.com/OpenPTrack/open_ptrack/wiki/Camera-Network-Calibration)?

**Comment by dagelabi** [comment]
Hey @marketto89 

Yes I did and tried re-doing them just to make sure I did not miss a step. Do you know what part of the calibration information OpenPTrack doesn't find ?

**Comment by marketto89** [comment]
In order to track down the issue I would need two things:
- the camera_poses.yaml file (it should be in the opt_calibration/conf folder) 
- the "frames.pdf" resulting from `rosrun tf view_frames`. Of course, you should run the command with the system powered on (after having launched the trackers/detectors)

**Comment by dagelabi** [comment]
There you go
[Dagelabi_OPT_network+frames.zip](https://github.com/OpenPTrack/open_ptrack_v2/files/1674385/Dagelabi_OPT_network.frames.zip)

**Comment by marketto89** [comment]
The split trees in your frames file seem like a bug in the ZED calibration framework.

Could you please manually change all the occurrences of "zed_suivi" to "zed_suivi_link" and "zed_camera_1" to "zed_camera_1_link" in your opt_calibration_results.launch (opt_calibration/launch folder)? Do the ZEDs detect anything with the proposed change (you need to run again tracker and detectors)?

**Comment by dagelabi** [comment]
Hey @marketto89 ,

I added the '_link' for every occurrences and now I receive data when I launch the tracking :+1: . However it looks like my cameras are not correctly oriented in my 3D space. ( see the wooden floor in the picture )
![dagelabi_opt_test](https://user-images.githubusercontent.com/16769795/35588238-f5fa6844-05cd-11e8-9462-44ded250a37e.png)

Also, would I need to change the 
`node pkg="tf" type="static_transform_publisher" name="zed_suivi_broadcaster"`
to
`node pkg="tf" type="static_transform_publisher" name="zed_suiv_link_broadcaster"` ?

**Comment by marketto89** [comment]
ok, we have the confirmation that there is a missing transformation from zed_suivi to zed_suivi_link (for each zed). 

Unfortunately, I did not use the ZED too much so I need to make a calibration test here to fix this problem. 

Regarding the question on the change, no it is not needed you do that, the change I was mentioning was only about exact names not prefixes.

**Comment by dagelabi** [comment]
Hey @marketto89  did you have time to do some tests with the ZED, or is there something I could provide you to help you work on that issue ?

Thanks !

**Comment by marketto89** [comment]
Hey @dagelabi, 

sorry for the delay, but we got some problems with our ZED camera which is preventing us from using it. For this reason, it is difficult to reproduce the calibration error and, therefore, to solve it. 

The issue we are facing is not that easy to fix, since it is a bug in the ZED SDK we are using which has only been solved in the newer versions of the SDK. Nevetheless, changing the SDK would mean updating to CUDA 9 which will break everything else in OPT.

We'll let you know as soon as we have news on this issue.

**Comment by dagelabi** [comment]
Hello @marketto89,  Is there's any update on the ZED integration?

Thanks!

**Comment by jburkeucla** [comment]
Zed integration now available.
