### ISSUE TITLE
OpenPTrack skeleton joints model

### ISSUE THREAD

**Issue by mnemllr** [OpenPTrack/open_ptrack_v2#113]
Hello, 

The 15 body joints of the pose annotation data look like this:

{ 
...
"joints": {
            "model":"rtpose_MPI",
            "HEAD"
            "NECK"
            "RSHOULDER"
            "RELBOW"
            "RWRIST"
            "LSHOULDER"
            "LELBOW"
            "LWRIST"
            "RHIP"
            "RKNEE"
            "RANKLE"
            "LHIP"
            "LKNEE"
            "LANKLE"
            "CHEST"}

1. Why the OPT skeleton has not 17 joints like the [OpenPose skeleton](https://www.researchgate.net/figure/An-example-of-the-skeleton-representation-obtained-using-the-OpenPose-library-a-shows_fig1_326111194) (eyes, ears)?

2. Can I change the skeleton model in OPT?

3. Where is the exact position of the HEAD joint? Middle, front top of the head? Is there a picture of the OPT skeleton model?

4. I saw OpenPose Finger Tracking, thats not possible with OPT right?

Thanks you in advance :)

**Comment by mnemllr** [comment]
Not any hints?
I mean where is, e.g., the joint CHEST located? The OpenPose COCO or BODY_25 skeleton knows only HEAD and NECK, no CHEST.

![image](https://user-images.githubusercontent.com/58310415/71099548-bfdcc280-21b3-11ea-8f91-9eb593435862.png)

**Comment by bsubbaraman** [comment]
1. We're using an older version of OpenPose, [rtpose ](https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose) and by default we use with the MPI model which uses 15 joints for faster performance. Updating to the new OpenPose is on our radar (#48). 

2. You should be able to change to the COCO model which uses the 17 joints you mention by editing [the skeleton detection launch file.](https://github.com/OpenPTrack/open_ptrack_docker_config/blob/1804/single_camera_tracking/open_ptrack_config/detection/launch/skeleton_detector_realsense.launch).. but now that you mention it, I took a look and it seems to [still use the MPI model](https://github.com/OpenPTrack/open_ptrack_v2/blob/3fb6f8d237731ebf169d76cd367419c01d2c08ae/detection/launch/skeleton_detector.launch#L19) even when coco is enabled. In any case, I'd start with these files if you want to get the 17 joint model working.

3. Qualitatively, the 15 joints are positioned like this:
![image](https://user-images.githubusercontent.com/11969085/71114735-4c23c100-2185-11ea-9f4e-0c0a1e17db97.png)

So the chest is joint 14. Empirically, the head joint is approximately at the center of the head.

4. Hand/finger tracking isn't possible with OPT as of now (see #42) and won't be possible until we update to the newer OpenPose.

I hope this helps, let me know if there are any more questions/clarifications about this!

﻿﻿

**Comment by mnemllr** [comment]
Thank you very much, helps me a lot!

**Comment by bsubbaraman** [comment]
Great! Closing the issue.
