### ISSUE TITLE
Object tracking data

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#117]
Hello,

For my VR application I want to track some objects (e.g. a box) and bring them into VR.

1. What is meant by "height" in the object tracking data? The size of the object or the z coordinate?
2. Is the coordinate system in the center of the object or where do the x and y coordinates point to?

```
   "object_tracks": [{
        "id": 387,
        "object_name": "ball_red",
        "x": -0.89131,
        "y": 2.41851,
        "height": 1.55837,
        "age": 29.471,
        "confidence": 0.0500193
    }]
```

Thanks!

**Comment by nanodust** [comment]
Hello Manuel,

The xyz origin is set during extrinsic calibration.  One uses the grid to
set the zero point on the floor per wiki.

All tracking is then in meters, from that origin.

**Comment by muella91** [comment]
@nanodust  Thanks for your answer, but that was not my question. I already did the extrinsic calibration, I know all positions are measured from the OPT world coordinate system.
My questions are:

**1. What is meant by "height" in the object tracking data? The size of the object or the z coordinate?
2. Is the coordinate system in the center of the object or where do the x and y coordinates point to?**

I hope the following picture makes my questions clearer.
![objectTracking](https://user-images.githubusercontent.com/41471198/72216441-5e451500-3521-11ea-87bd-cac37ba06933.jpg)

**Comment by jburkeucla** [comment]
Height is the z-coordinate. In position and object tracking, the coordinates generally refer to the centroid.  (In person tracking, it's more practically the centroid of the upper body, usually.)

**Comment by muella91** [comment]
@jburkeucla Perfect, thanks for your answer!
