### ISSUE TITLE
Multiple Cameras/Dockers on one Computer

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#118]
Hello,

For Pose Tracking, I want to test multiple Camera Nodes on one Computer. I know it will take a lot of computing power, but I got a pretty sick gaming PC.

Could you give me some instructions how to run multiple Dockers on one Computer?

Thanks!

**Comment by bsubbaraman** [comment]
Hi @muella91, 
What are you imager types? Are they two of the same (two kinect, two zed, etc) or two different imagers?

To run two imagers in a camera network from a single machine you will use the same docker container, it will just require setting up the `camera_network.yaml` file appropriately. Two imagers of different types (e.g. 1 zed and 1 kinect) is straightforward and requires nothing different than a normal set up. If you are using two kinectv2s, please see [this section](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Pre-Calibration-File-Configuration#2-create-files-for-multi-sensor-calibration), and the `serial` subsection that refers to `libreenect2`'s requirements for multiple Kinects. Things should work out-of-the-box on the OpenPTrack side for running two Kinects, but let us know if you run in to any problems.

Running 2 Zed or 2 RealSense from a single machine _should_ also work, but this is untested as we currently only have one of each imager.

**Comment by muella91** [comment]
Thanks for your answer.
I will use two Kinects v2.
I will follow your instructions and post the result.

**Comment by bsubbaraman** [comment]
Great - closing this issue now so that any specific problems/errors encountered get their own thread.
