### ISSUE TITLE
Coordinate origin on Kinect v2 with single-camera tracking

### ISSUE THREAD

**Issue by mnemllr** [OpenPTrack/open_ptrack_v2#122]
Hello,

Since I need to transform the OpenPTrack joint coordinates to a different coordinate system, I need the exact position of the origin on the Kinect v2.

The original MS Kinect v2 origin lies on the depth sensor, I guess on the front surface of the Kinect v2:
![Kinectv2Origin](https://user-images.githubusercontent.com/58310415/73918881-c4278100-48c2-11ea-880b-04d805864803.JPG)

Am I right in assuming that you choose the same origin, that your coordinate axes have a different orientation? I assumed the following OPT single-camera coordinate origin/orientation:
![Kinectv2OPTOrigin](https://user-images.githubusercontent.com/58310415/73918971-eb7e4e00-48c2-11ea-8a0c-aea4680f93aa.jpg)

Thanks for your help!

**Comment by mnemllr** [comment]
Issue can be closed.

OPT Single Camera Pose Tracking origin lies exactly as I assumed in the second picture above.
The origin has aproximately following position:
![Bild2](https://user-images.githubusercontent.com/58310415/75460698-13247b80-5982-11ea-8930-a03f3799bdbd.jpg)

X-origin lies on the front surface of the camera.

**Comment by bsubbaraman** [comment]
Cool- closing!
