### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ugintl** [OpenPTrack/open_ptrack_v2#130]
Is docker our only option?

After it is installed, how to use it?

**Comment by bsubbaraman** [comment]
Docker is the easiest and recommended installation option. ([Manual build and installation](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Manual-Build-and-Installation) is also available, though the steps provided are not updated to reflect all changes made in [OPT v2.2](https://github.com/OpenPTrack/open_ptrack_v2/releases/tag/v2.2); if you _do_ wish to manual build, I'd recommend taking a look at the [Dockerfiles](https://github.com/OpenPTrack/open_ptrack_v2/blob/1804/docker/open_ptrack-dep/Dockerfile) in the 1804 branch as well.)

After you get the Docker image, you can proceed directly to the [single camera tracking instructions](https://github.com/OpenPTrack/open_ptrack_v2/wiki/single-camera-person-tracking) if you have only one imager or wish to test the installation. For a multi-camera setup, proceed to [configuration](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Configuration) followed by [calibration](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Calibration). You should be able to move down the sidebar of the wiki to find out what to do next.

Happy tracking!
