### ISSUE TITLE
Compatibility with the ZED Mini

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#131]
Hey,

According to [this post](https://support.stereolabs.com/hc/en-us/articles/360009984434-What-is-the-difference-between-the-ZED-and-ZED-Mini-), ZED and ZED Mini seem to pretty comparable (except the tracking range).
Does OpenPTrack v2 run also with the ZED Mini or have you tested it?

Thank you!

**Comment by jburkeucla** [comment]
Yes, we have successfully tested on the Zed mini.
