### ISSUE TITLE
Performance when tracking

### ISSUE THREAD

**Issue by dagelabi** [OpenPTrack/open_ptrack_v2#16]
Hi,

Since the ZED is not yet ready for OPTv2, I've continue to test it with 2 Kinects. 

My setup constist of two computer 
**Slave**    : Detection with 1 Kinect v2
**Master** : Detection with 1 Kinect v2 + Tracking 

During my testing sessions, I kept an eye on the performance window and I realize that : 
When nobody was tracked the CPU on both computer shown 80% of it's maximum capacity
When somebody is tracked ( 1 person or more ) my CPU jumps to 100% 

Both computers has an **Intel - Core i7-7700K 4.2GHz** and an **NVIDIA GeForce GTX 1070**
With that kind of hardware I was hoping to drive two imagers with one computer or combining the tracking calculation and an imager.

Are those results normal ?

First image      : Slave ( Two people were tracked in the begining and left the scene at the end )
Second image : Master ( Two people were tracked towards the end of the graph )

![vor002_tracking_2_peoples_performance_slave](https://user-images.githubusercontent.com/16769795/38384394-0a4c1166-38dd-11e8-9e73-1a94e26f33b0.png)
![vor002_tracking_2_peoples_performance_master](https://user-images.githubusercontent.com/16769795/38384395-0a5b8916-38dd-11e8-825f-989c9aac93b3.png)

Thanks !
-Dage

**Comment by jburkeucla** [comment]
Alexandre,

Sorry that the Zed’s not working for you yet.

This CPU utilization is not consistent with what we’ve seen on similar and less powerful CPU/GPU combinations. The load seems high.

Can you send info on GPU utilization as well? I think nvidia-smi should provide

Jeff

**Comment by dagelabi** [comment]
Hey Jeff, Unfortunately, I'm not near my OPTv2 setup, but I'll send hose result as soon as I can!

**Comment by dagelabi** [comment]
Hey Jeff,

have you had a chance to review this issue ?

Thanks

**Comment by jburkeucla** [comment]
Sorry, not yet – we will look this week.
Best,
Jeff

**Comment by martyi** [comment]
Hello,
i make a fresh install on ubuntu 16.04 with two big config computer : 

client : 
1060 gtx 6gb vram 
cpu i5 3.30GHZ x 4 
memory 16GB

server :
1080 gtx
cpu i7 3.60GHZ x 8
memory 16GB

and when I am running : 
`roslaunch detection detection_node_kinect_02.launch`

I am getting this message "skipping rgb packet !" 

![screenshot from 2018-07-12 13-23-09](https://user-images.githubusercontent.com/13206752/42630688-fa1c0f74-85d7-11e8-8c2d-3222891ebe0c.png)

I am digging your project and lot of issue on github and I read that it can be a performance issue 
And indeed my cpu run this with 100% usage 
result : 

![screenshot from 2018-07-12 13-22-27](https://user-images.githubusercontent.com/13206752/42630761-418a7c74-85d8-11e8-9569-c2d19b65940e.png)

![screenshot from 2018-07-12 13-22-42](https://user-images.githubusercontent.com/13206752/42630763-441ed412-85d8-11e8-9f7e-928c1f3eed21.png)


Is it normal ? 
how can i improve/optimize this ? 
how can i be sure that i am using all my gpu performance ?
And if it's normal how can i disable feature to optimize this ?

thanks

**Comment by dagelabi** [comment]
Any update on that issue ?

**Comment by nanodust** [comment]
Does it still detect and track ?

I do get the same RGB packet error regularly (especially with usb 3.0
extender) yet I am still able go detect and track reliably.

I'm on an i7 w 16GB ram

**Comment by jburkeucla** [comment]
No response for ~1 yr. Closing issue.
