### ISSUE TITLE
ZED works with v2 or not?

### ISSUE THREAD

**Issue by jingfeng-linksprite** [OpenPTrack/open_ptrack_v2#17]
I followed the google doc, and install everything until I do the single camera tracking.

 roslaunch tracking single_camera_tracking_node.launch

The ZED is working when I do:
/usr/local/zed/tools/ZED\ Diagnostic

However,

in  roslaunch tracking single_camera_tracking_node.launch,

I got:
Freenect2Impl] enumerating devices...
[Freenect2Impl] 7 usb devices connected
[Freenect2Impl] found 0 devices
Error: no Kinect2 devices found!
Initialization failed!

**Comment by jburkeucla** [comment]
Zed integration has been recently completed.
