### ISSUE TITLE
V2 Kinect2 Detection - 

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack_v2#18]
Hello, 

I've followed all [v2 install instructinos](https://docs.google.com/document/d/1iagy-zU1cbV92YQI6EJhieM5-09BGrVsVmmz0QjK0XA/edit)
(skiping over ZED)

they worked well - or seemed to, no errors.

yet when i 
`
roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=true enable_object:=false
`
I get

`
[kinect2_head_kinect2_bridge-6] restarting process
process[kinect2_head_kinect2_bridge-6]: started with pid [4396]
/home/nomo/workspace/ros/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/nomo/workspace/ros/devel/lib/libdepth_registration.so)
/home/nomo/workspace/ros/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/nomo/workspace/ros/devel/lib/libdepth_registration.so)
/home/nomo/workspace/ros/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/local/lib/libfreenect2.so)
/home/nomo/workspace/ros/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/local/lib/libfreenect2.so)
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[kinect2_head_kinect2_bridge-6] process has died [pid 4396, exit code -6, cmd /home/nomo/workspace/ros/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/nomo/.ros/log/6bedbd48-5494-11e8-9fa6-80ee73a74cf2/kinect2_head_kinect2_bridge-6.log]
`

I recall this from prior work w/ v1 - I will try to debug more... 

meanwhile, asking for any tips / advice 

thanks !

**Comment by legshampoo** [comment]
nanodust - it seems like my issue had to do with my cuDNN installation.  I re-installed Cuda following the instructions on their site, and re-installed cuDNN as well.  Seems to have fixed the error for me

**Comment by lthursdayl** [comment]
@nanodust did you trying following @legshampoo 's suggestion? If so did it resolve the error?

**Comment by nanodust** [comment]
@lthursdayl no, I did not - fact is, I was trying this on an old v1 shuttle, and I need a faster GPU to do the pose detection in v2. I'm still waiting for the new hardware to arrive, at which point I'll give this all another shot.

**Comment by lthursdayl** [comment]
@nanodust oh, okay. Thanks for the update. We are hoping to have the OPT v2 Wiki updated by the end of the summer which should help resolve some of the installation errors.
