### ISSUE TITLE
build error: opt_msgs

### ISSUE THREAD

**Issue by mattslathrop** [OpenPTrack/open_ptrack_v2#21]
When running catkin_make in the install guide (https://docs.google.com/document/d/1iagy-zU1cbV92YQI6EJhieM5-09BGrVsVmmz0QjK0XA/edit) I get the error 

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "opt_msgs" with any
  of the following names:

    opt_msgsConfig.cmake
    opt_msgs-config.cmake

  Add the installation prefix of "opt_msgs" to CMAKE_PREFIX_PATH or set
  "opt_msgs_DIR" to a directory containing one of the above files.  If
  "opt_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  open_ptrack/opt_gui/CMakeLists.txt:22 (find_package)

Any ideas of what I am doing wrong in the install?

**Comment by SimeonOA** [comment]
Hi,

We think this is a recent issue with one of our dependencies. We are looking into it and will get back to you. 

Simeon

**Comment by mattslathrop** [comment]
I managed to get it to build by calling catkin_make --only-pkg-with-deps with first opt_msgs then opt_gui then all the other packages. However now the yolo detector isn't working properly so that might be related? #22

**Comment by SimeonOA** [comment]
Hi,

Thank you for pointing out this issue.

Please check out and use  the branch [iss21](https://github.com/OpenPTrack/open_ptrack_v2/tree/iss21). We have recently updated it. This should take care of both the build error and the YOLO detector issue.

Simeon

**Comment by bsubbaraman** [comment]
Closing as this issue has been resolved.
