### ISSUE TITLE
ERROR can't locate node

### ISSUE THREAD

**Issue by rmtttt** [OpenPTrack/open_ptrack_v2#23]
Hello,

I'm successfully building from branch iss21, but when I run 
`roslaunch tracking yolo_detection_and_tracking_kinect.launch`
or
`roslaunch tracking yolo_detection_and_tracking_zed.launch`
I'm getting an error:

> ERROR: cannot launch node of type [yolo_detector/open_ptrack_yolo_detector_node]: can't locate node [open_ptrack_yolo_detector_node] in package [yolo_detector]

Of course, tracking is not working.
I tried many things, and already don't have any ideas.. Can you help me to find out the problem please.

Alex

**Comment by RaymentV** [comment]
`roslaunch detection_and_tracking_zed.launch`

leads to

> [detection_and_tracking_zed.launch] is not a launch file name
> The traceback for the exception was written to the log file

**Comment by youpicontini** [comment]
Hello there,
I had the  #21  aswell, I succesfully built from branch iss21. and then succesfully built again from master branch.
I have the same error 

`ERROR: cannot launch node of type [kinect2_bridge/kinect2_bridge]: can't locate node [kinect2_bridge] in package [kinect2_bridge]
`

but from the command
 `roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=false enable_object:=false
`
My GUI is running but no kinect is found. Also, I've been able to test my kinect with libfreenect and it works.

Hope it helps,

Alex

**Comment by bsubbaraman** [comment]
Closing as this issue has been resolved.
