### ISSUE TITLE
[software architecture question] point cloud on 3rd party app

### ISSUE THREAD

**Issue by youpicontini** [OpenPTrack/open_ptrack_v2#24]
Hello, 
I would be interested in transmitting the full pointcloud (from all the sensors with the rotation/translation) to a 3rd party app, probably open frameworks, on another computer/ other OS.

Do you have any idea on where to get this full point cloud in the code or if not, where to get the pointclouds seperately?

Also, would you recommend a transmission protocol to get this done? PCL seems the best, but I'm just asking.

Great work on the gnocchi version!
Alex

**Comment by SimeonOA** [comment]
Hi Alex

The registered point cloud can be accessed via ROS topics.

If you are just looking to display it, you can make use of Rviz  see [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz)  but if you are looking to extract it, you have to write some code using a ROS library. 

Please let us know if you have any other questions

Simeon
