### ISSUE TITLE
Single Camera Tracking not working

### ISSUE THREAD

**Issue by arvindaccel** [OpenPTrack/open_ptrack_v2#25]
Hello,

I'm running the docker container for OpenPTrack and have been able to connect a Kinect V2 sensor and do intrinsic calibration on the camera. The Kinect is positioned about 1.5m above the ground and has clear visibility.

Then, as the google doc instructs, I run `roslaunch tracking single_camera_tracking_node.launch`. The RViz window and 'Select 3 Points' windows each pop up. In the 'Select 3 Points' window, I select 3 points on the mostly visible ground.  Another Camera Legend window pops up after a certain period of time. The terminal output seems normal and as expected.

In the Rviz interface, I have gotten pose detection as well as object detection displaying in the camera view and skeletons displaying on the grid. However, I am not able to view person tracking. In 'Tracking Marker', 'Tracking History', and 'Marker Array' I haven't been able to see the results of the /tracker/markers_array and /tracker/markers_array_smoothed at all. At times, they appear to be receiving images and are not throwing errors or warnings, but there is no visual result from the topics in Rviz. 

In the 'Tracking History' I have seen 'Transform [sender=unknown_publisher]' but I'm not sure if this is affecting tracking. At this point I have ruled out hardware as a cause as I have confirmed that the Kinect is working with Protonect, have a fairly decent workstation gpu setup, and have tried running tracking alone in the single camera tracking demo. I think that there is some setting that I'm missing here and I would greatly appreciate any advice. Let me know if there's anything else that I can add here that I've missed.

![My Rviz Setup](https://user-images.githubusercontent.com/37342998/43107126-6d647924-8e90-11e8-9fda-2974992e2568.png)

**Comment by arvindaccel** [comment]
I ran that command as well as other combinations of true and false for the other features. When tracking is isolated like in that command, there is a Fixed Frame error. This doesn't happen with any other combination, though. No tracking functionality.
![fixedframeerror](https://user-images.githubusercontent.com/37342998/43151871-c8770dd6-8f21-11e8-9a62-86b13bb16994.png)

I tried changing the fixed frame to /kinect2_head_rgb_optical_frame like it has been suggested in the V1 repo. The global status was resolved, but then tracking history broke and tracking doesn't work:
![trackinghistorybroken](https://user-images.githubusercontent.com/37342998/43151958-05112448-8f22-11e8-8fdb-f87c33ff6a90.png)
 
I've also tried the other available fixed frames such as link and ir but without luck.

**Comment by SimeonOA** [comment]
Hi 

3D tracks of people should also show up in single camera tracking.

It is quite possible you are doing the floor estimation in the wrong way. Try changing the ground estimation algorithm as well as ensure you are using the correct Rviz file.

Simeon

**Comment by bsubbaraman** [comment]
Closing as this issue has been open a while and we haven't been able to reproduce. Please re-open if this issue persists with our most recent updates!
