### ISSUE TITLE
Compiling error, No such file or directory #include <rtpose_wrapper/SkeletonMsg.h>

### ISSUE THREAD

**Issue by ivellioscolin** [OpenPTrack/open_ptrack_v2#28]
Ubuntu 18.04, ros is built and configured from source as suggested by: http://wiki.ros.org/melodic/Installation/Source.

After manually resolve build depends as some of scripts under ./scripts, run catkin_make --force-cmake to make open_ptrack_v2. However met compiling issue:

/home/user/workspace/ros/catkin/src/open_ptrack_v2/detection/include/open_ptrack/detection/skeleton_detection.h:49:10: fatal error: rtpose_wrapper/SkeletonMsg.h: No such file or directory
 #include <rtpose_wrapper/SkeletonMsg.h>

The referred repo seems empty:
https://github.com/OpenPTrack/rtpose_wrapper.

Any suggestion?

**Comment by SimeonOA** [comment]
Hi,

OpenPTrack v2 is currently only supported on Ubuntu 16.04 and uses ROS Kinetic.   Please see Supported Hardware<https://github.com/OpenPTrack/open_ptrack_v2/wiki/Supported-Hardware>.

Also, the installation options for OpenPTrack v2 are  found here<https://github.com/OpenPTrack/open_ptrack_v2/wiki/Build-and-Install>. We recommend that less experienced users of OpenPTrack v2 use our Docker Images<https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images> installation.

Please let us know if this solves your problem or if you need more help.

Thanks

Simeon

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ivellioscolin** [comment]
Thanks for the quick response. I'll try the docker image. 
Thanks.
