### ISSUE TITLE
Pose Annotation not working in Single Camera without people tracking & Visualization Issues

### ISSUE THREAD

**Issue by SimeonOA** [OpenPTrack/open_ptrack_v2#29]
We found out that Pose Annotation  does not work in Single Camera without the person tracking flag enabled. 
So instead of : 

`roslaunch tracking single_camera_tracking_node.launch enable_pose:=true enable_people_tracking:=false enable_object:=false`

we have to use:

`roslaunch tracking single_camera_tracking_node.launch enable_pose:=true enable_people_tracking:=true enable_object:=false`

I also had some Rviz visualization issues  in the Manual installation version of OPT while running Pose but I think that has to do with the options I was selecting and not the Annotation itself.

**Comment by jburkeucla** [comment]
@SimeonOA it may be resolved - can you test?

**Comment by SimeonOA** [comment]
Tested in 18.04 Docker using Kinect v2 and in 16.04 Docker using realsense.

Now works in both cases.

Will update wiki to reflect.
