### ISSUE TITLE
Can I use OPT v2(master) and OPT v1(host) together?

### ISSUE THREAD

**Issue by GyeoreLee** [OpenPTrack/open_ptrack_v2#31]
Hi,

Currently, I'm trying to install OPT v2.
But my host PC doesn't have GPU so i need to use OPT v1 for detection.

When I ran the (roslaunch opt_calibration calibration_initializer.launch) from master and (roslaunch opt_calibration listener.launch) from host to calibrate camera network, I faced the error about service call md5 hash mismatch.

Is it possible to use both version simultaneously?

Thank you.

**Comment by SimeonOA** [comment]
Hi,

We do not recommend combining the installations for V1 and V2. It is possible to use the basic person tracking in V2 without a GPU and you should try that. 

However note that the Kinect 2 requires a GPU for processing so this depends on your imager. 

Please let us know if you have any other questions.

Simeon
