### ISSUE TITLE
driver versoins of cuda and zed for open_ptrack_v2 

### ISSUE THREAD

**Issue by gnoopy** [OpenPTrack/open_ptrack_v2#32]
Hello. Today I've tried open_ptrack_v2  with kinect v2 and could handle it working.
In the mean time I noticed that kinect might be sunset soon. Because of this I tried open_ptrack_v2 with newly purchased ZED camera and faced version conflict.

Based on your guide CUDA 8.0 + opencv 3.3.1 is given for your working environment. 
But the new ZED camera with SDK 2.4 is not working with CUDA 8.0. Since this incompatible versions ZED might not be working with open_ptrack_v2. If I use ZED SDK 2.0.1 as guided by open_ptrack_v2 document, Ubuntu cannot recognize the device. I guess the new device only works with the higher version of SDK.

Is there any way I could solve this?

**Comment by jburkeucla** [comment]
﻿Thanks for trying OpenPTrack!  We are working on fixing the Zed support in September, and will update this issue with more information.

**Comment by gloriauni** [comment]
hello. there are any updates about this issue?

**Comment by dagelabi** [comment]
I'm also interested to know if there's any updates

**Comment by radisc** [comment]
About the new branch zed_latest, does it follow the same procedure and dependancies version as the master branch?

**Comment by bsubbaraman** [comment]
Support for the Zed and RealSense is now available on the 1804 branch (OPT v2.2). There are notes on the driver version in the [wiki](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images#installation)!
