### ISSUE TITLE
ZED camera pose detection plans

### ISSUE THREAD

**Issue by thomaswester** [OpenPTrack/open_ptrack_v2#33]
I was hoping to use multiple ZED camera's for pose detection. I am able to get the ZED camera to work but noticed that pose detection has been disabled. 

Is there a specific reason why pose detection was removed for ZED, is there a way I can enable it or help contribute to enabling this. 

Kinect v2 is not a option for me as the sensor causes interference with other components in the experience.

**Comment by jburkeucla** [comment]
This is imminent, please check back in ~1 month or less.

**Comment by bsubbaraman** [comment]
Pose tracking for Zed is up and running using the 1804 branch/OPT v2.2. See [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images#installation) for more info!
