### ISSUE TITLE
"sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi" fails with cuda > 9.0-basic

### ISSUE THREAD

**Issue by crankbird** [OpenPTrack/open_ptrack_v2#34]
Following the instructions https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images fails at the step that checks to see if the nvidia drivers are working.

I spent a while (a couple re-installs from scratch on a fresh system and trying a rebuild from sources) troubleshooting this, and found that it appears to be related to https://github.com/NVIDIA/nvidia-docker/issues/832 ..

on a completely fresh ubuntu 16.04 install following the instructtions resultein the the command

 sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-sm 

giving the following  error

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=5346 /var/lib/docker/overlay2/bf554405c63b53fe8458e1c130c14c2f81db21bcb96472361c0f8423bf277f76/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.

In the end I found that 

"sudo docker run --runtime=nvidia --rm nvidia/cuda:8.0-devel  nvidia-smi"  works, as does "sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-basic nvidia-smi". with results similar to the following

   Wed Oct 10 09:54:38 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 670MX   Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   49C    P8    N/A /  N/A |    192MiB /  3017MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

From my research, it appears that the latest version of the nvidia/cuda container is incompatible with driver version 384.130 which seems to be a requirement for open_ptrack_v2.

May I suggest that the documentation is updated to reflect this while someone identifies if a more recent driver and updated install scripts etc would be a better long term fix ?

**Comment by david-waterworth** [comment]
This is my exact experience as well. In order to get all the images to work, I had to install cuda 10.0 with driver version 410.48 on the host, for cuda:9 and earlier images I could get away with cuda 9.0 and 384.130

**Comment by SimeonOA** [comment]
Hi crankbird, 

Thank you for this.

We have updated the documentation to reflect the command using cuda 8 as the current version of OPT uses cuda 8.

Please let us know if you need anything else.

Simeon

**Comment by titusfx** [comment]
@david-waterworth can you explain how did you do that? Just to be sure I'm doing the same steps than you. I'm having the exact problem that you had [on](https://github.com/NVIDIA/nvidia-docker/issues/832#issuecomment-425605760) where:

where this works:
`docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`

 but this

`docker run --runtime=nvidia --rm nvidia/cuda:10.0-base nvidia-smi`

fails with error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=4376 /var/lib/docker/overlay2/2c038e7fffd0f9304aeb23f1a724a5669a60dd01b2ec29343acf6eac49a78b00/merged]\\\\nnvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.`

**Comment by david-waterworth** [comment]
@titusfx I generally follow the instructions from [https://www.pugetsystems.com/labs/hpc/How-To-Install-CUDA-10-together-with-9-2-on-Ubuntu-18-04-with-support-for-NVIDIA-20XX-Turing-GPUs-1236/](here) [up to an including step 5]

Only issue is the deb file version upgrades to the latest release so you'll end up with CUDA 10.1 instead of 10.0 if you follow these instructions. If you specifically need 10.0 then where it says `sudo apt-get install cuda` do `sudo apt-get install cuda-10-0`

Alternatively the runfile method is more complicated but it works fine as well

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile
