### ISSUE TITLE
people tracking ID change

### ISSUE THREAD

**Issue by gnoopy** [OpenPTrack/open_ptrack_v2#37]
Hello, I am really happy to start using open ptrack v2 on my system. 
While I play around with this, I found out that the marker numbers change unexpectedly when I raise my hands for a while during walking. 
For instance, my body was marked 5 on the Grid, my hands marked as 6 and 7 for each side and my body marked as 7 after I put down my arm and hands back.
Is there some good way to ignore these numbers being marked for hands or arm so that person's body keeps the ID number as long as possible?

**Comment by bsubbaraman** [comment]
If I'm understanding correctly, you are referring to the pose tracking joint ids which are changing. While these IDs may change more rapidly, the ID of the skeleton track is the unique identifier that should not change while the skeleton is being detected. More info on the data format can be found [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Using%20The%20Data). Please let me know if I've misunderstood the question!
