### ISSUE TITLE
Calibrate using pictures

### ISSUE THREAD

**Issue by inders** [OpenPTrack/open_ptrack_v2#38]
Is it possible to calibrate using pictures rather than live data recorded from this software which limits it's usage to certain cameras like Kinect?

**Comment by jburkeucla** [comment]
Unfortunately that is not a supported approach.



________________________________

**Comment by inders** [comment]
Thanks @jburkeucla I have real sense cameras. Any thoughts if they would work with new release.

**Comment by bsubbaraman** [comment]
Closing as the question has been answered.
