### ISSUE TITLE
Finger and hand gesture detector?

### ISSUE THREAD

**Issue by oless** [OpenPTrack/open_ptrack_v2#42]
Hello, 
Does anyone know if there is a known way of doing not just pose recognition but continued gesture recognition? Thank you.

**Comment by jburkeucla** [comment]
﻿This is not currently supported

**Comment by oless** [comment]
I would be interested in helping to add this functionality in. Would you be able to give me a few pointers on how to implement this best, so that it still works with your overall design structure? At which point in the process should I add this functionality? I assume while parsing the point cloud...?

**Comment by jburkeucla** [comment]
Happy to try to help you in adding a module.  (Sorry for the delay in responding to the issue.) If  you are still interested in doing this, please let us know.
