### ISSUE TITLE
iai_kinect2 1604 branch doesnt exist

### ISSUE THREAD

**Issue by Harsharma2308** [OpenPTrack/open_ptrack_v2#45]
As given [here](https://docs.google.com/document/d/1iagy-zU1cbV92YQI6EJhieM5-09BGrVsVmmz0QjK0XA/edit), I do not find 1604 branch in the iai_kinect2 repository.
The master branch doesn't have kinect_bridge_ir.launch. 
So what is the solution?

**Comment by SimeonOA** [comment]
Hi, 

Please refer to the the Wiki [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Build-and-Install) for instructions on how to build and install OpenPTrack. The document you linked is not the most updated. For first time users we often recommend the Docker Images 

As regards the 1604 branch, it is in the OpenPTrack/iai_kinect2/ repository as shown [here](OpenPTrack/iai_kinect2/). 

Please let us know if you have any other questions.

Simeon

**Comment by Harsharma2308** [comment]
I see. Thanks for this info.
