### ISSUE TITLE
No node named 'multiple_object_detection_node' inside detection package

### ISSUE THREAD

**Issue by Harsharma2308** [OpenPTrack/open_ptrack_v2#47]
On launching-
`roslaunch tracking single_camera_tracking_node.launch enable_pose:=false enable_people_tracking:=false enable_object:=true
`
I get this error-
`ERROR: cannot launch node of type [detection/multiple_objects_detection_node]: can't locate node [multiple_objects_detection_node] in package [detection]
`

Which seems to be correct as detection package's CMakeLists.txt doesn't create any executable named multiple_object_detection_node.

But this node is called in the launch file, _single_camera_tracking_node.launch_ of tracking package.

**Comment by MikoyChinese** [comment]
You can see this https://github.com/OpenPTrack/open_ptrack_v2/commits/master/detection/CMakeLists.txt.
Itabr committed on Sep 28, 2018 and he removed multiple_objects_detection from detection CMakeLists.txt. If you wanna run this node, find the old file to build it again.

**Comment by SimeonOA** [comment]
Hi,

Thanks for bringing this up. The launch files have been updated.

This issue should now be resolved.

Please let us know if you are still having this issue or have any other questions.

Thanks 
Simeon

**Comment by bsubbaraman** [comment]
Closing as this was resolved.
