### ISSUE TITLE
Tracking with a mounted single Kinect v2

### ISSUE THREAD

**Issue by gitarja** [OpenPTrack/open_ptrack_v2#49]
Hello, 
I just installed OpenPtrack and it worked using single Kinect v2. However, the skeleton tracking is rendered properly in Rviz world when I put the Kinect on the floor. The result was not good when I mounted it on the wall. I already did calibration and manual ground plane selection.

Thank you for any response

**Comment by gitarja** [comment]
@SimeonOA 
Hi,

Yes, I mounted it before doing the calibration and manual ground plane selection. The position of the Kinect still on the floor like the default setting.

Best regard,

Prasetia Utama Putra

**Comment by bsubbaraman** [comment]
Closing as we haven't been able to reproduce this issue. Please feel free to re-open if this issue persists using our most recent updates!
