### ISSUE TITLE
Realsense Frame metada isn't avaliable!(frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)

### ISSUE THREAD

**Issue by MikoyChinese** [OpenPTrack/open_ptrack_v2#54]
These days I try to use realsense D435 to run this repository, and I checkout the dev branch and change some code. But when I run object tracking with more than two D435 camera, I got the error about "transform exception: Lookup would require extrapolation into the past." And I check my ntp status, it's less than 10ms most time. So I am so cofusing. 

And then I also found that my master PC's terminal show that WARING: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME).

Any body help me?

**Comment by nanodust** [comment]
10 ms is too long for a lan setup... imho its worth configuring ntp to get
that down.

**Comment by bsubbaraman** [comment]
Regarding the warning: this [thread](https://github.com/IntelRealSense/realsense-ros/issues/803) from the realsense-ros page indicates that the warning can be safely ignored as metadata attributes are not exposed/used by librealsense.
