### ISSUE TITLE
Wiki instructions CUDA-and-Other-Softwares fail

### ISSUE THREAD

**Issue by riebling** [OpenPTrack/open_ptrack_v2#55]
https://github.com/OpenPTrack/open_ptrack_v2/wiki/CUDA-and-Other-Softwares-Installation
In this wiki page, a specific Git branch '1606' is requested:
```
 git checkout 1606
```
Then later, instructions show
```
cd protonect
```
but that directory does not exist in revision 1606 of the libfreenect2 repository.
It's not clear what the 'right thing to do' is: MUST revision 1606 be used (in which case the protonect build steps will fail) or MUST the protonect build steps be performed (in which case revision 1606 is the wrong one)
Maybe it's clearer to someone who knows how `cmake` works :)

**Comment by SimeonOA** [comment]
Hi 

Thank you for bringing this to our attention.

We are looking into it and will keep you updated.

Simeon

**Comment by evalliETH** [comment]
Did you manage to solve this issue? I'm having the same problem.

Eugenio

**Comment by SimeonOA** [comment]
Hi 

We have updated the instructions.

The protonect folder is not needed anymore. 

Instead of 
 
`cd../examples/protonect`

you would only

 `cd..` 

and then run the build and make steps in the libfreenect2 root directory. 

Please let us know if you have any other issues. 

Thanks 
Simeon
