### ISSUE TITLE
Configuring IP settings for client machine/ No

### ISSUE THREAD

**Issue by Geitenkaas** [OpenPTrack/open_ptrack_v2#59]
Hi,

I'm just getting started with OpenPtrack and following the wiki but am confused about how to configure the 'opt_utils/conf/json_udp.yaml file' for my Touch Designer client on the network.

Where does Docker put the opt_utils folder? I've searched my PC but don't seem to have it.

Also, I have been unable to get the 'simple image' to show in RViz with my Kinect2- any known issues with this?

thanks,

Boyd

**Comment by bsubbaraman** [comment]
Inside of the docker container, navigate to `~/open_ptrack/opt_utils/conf` to find the `json_udp.yaml` file for configuration. In a recent [update](https://github.com/OpenPTrack/open_ptrack_docker_config/commit/b154c55ec8c22bffc3a48141d1e5b816d00950d4) to the open_ptrack_docker_config repo, this folder is also linked to the host machine when starting the Docker container, so you can edit it from the host machine as well. 

If you still have issues with the SimpleImage in Rviz, please open a new issue and we can try to help resolve it.
