### ISSUE TITLE
[request] External Data Visualization

### ISSUE THREAD

**Issue by dagelabi** [OpenPTrack/open_ptrack_v2#6]
Hi,

I think it would be very useful to have access to the visualization data outside of Rviz. In my case I will be using OpenPTrack's data in TouchDesigner and would love to include the 3D visualization in this environment.

Keep on the good work !
- Dage

**Comment by SimeonOA** [comment]
Hi Dage,

Thank you so much 

What type of visualization data were you interested in accessing?

Simeon

**Comment by bsubbaraman** [comment]
Information on using the tracking data (including in TouchDesigner) can be found [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Using%20The%20Data).
