### ISSUE TITLE
Bionic Release 404 Not Found [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by evalliETH** [OpenPTrack/open_ptrack_v2#60]
I am trying to install the PPAs for manual build and installation of the OpenPTrack project and after typing

`sudo add-apt-repository -y ppa:levi-armstrong/ppa`

I get this oputput:

`. . . 
Err:14 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu bionic Release 404 Not Found [IP: 91.189.95.83 80]
 . . . 
E: The repository 'http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

I don't know how to solve this issue and I am quite new with Linux OS, could someone help me please?

**Comment by SimeonOA** [comment]
Hi evalliETH,

Support for OpenPTrack is currently on Ubuntu 16.04. It seems you are trying to get it running on Ubuntu 18.04. See requirements [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Openptrack-System-and-Hardware-Requirements).

Also, if you are new to OpenPTrack, we would recommend using the [Docker Images](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images) as these already have all the requirements built in. 

Please let us know if you have any other questions.

Thanks

Simeon

**Comment by bsubbaraman** [comment]
Closing as this question has been answered.
