### ISSUE TITLE
Background + Ground segmentation

### ISSUE THREAD

**Issue by msacco22** [OpenPTrack/open_ptrack_v2#61]
I'm using the single camera tracking with a realsense d435 camera through the docker image. The point cloud obtained has a lot of distortion errors. Is there a way I could confirm how the background and ground segmentation are performing? I'd like to plot the plane from the coefficients obtained on Rviz to check the ground plane equation obtained. Is there a way I could do this through the Rviz GUI?

**Comment by evalliETH** [comment]
Hi,

I am using the single-camera tracking and I'll also need the equation of plane to implement a pointing action recognition system.
Does someone know how the ground plane is defined and/or how to define a plane in the 3D space in the FOV of the sensor?

Thank you,
Eugenio

**Comment by msacco22** [comment]
Hi @evalliETH 

I have managed to obtain visibility of the ground plane through a separate developed node. It subscribes to the pointcloud topic and read the ground plane coefficients from file. 

The little processing is done in the cloud callback:


```
// Global Variables

Eigen::VectorXf ground_coeffs;

// Clouds
PointCloudT::Ptr cloud(new PointCloudT);
PointCloudT::Ptr ground_cloud(new PointCloudT);


void cloud_cb (const PointCloudT::ConstPtr& callback_cloud)
{
    *cloud = *callback_cloud;

    pcl::IndicesPtr inliers(new std::vector<int>);

    boost::shared_ptr<pcl::SampleConsensusModelPlane<PointT> > ground_model(new pcl::SampleConsensusModelPlane<PointT>(cloud));
    ground_model->selectWithinDistance(ground_coeffs, 0.06, *inliers);
    
    pcl::ExtractIndices<PointT> extract;
    extract.setInputCloud(cloud);
    extract.setIndices(inliers);
    extract.setNegative(false);
    extract.filter(*ground_cloud);
}

```
