### ISSUE TITLE
Intrinsic Calibration Problem

### ISSUE THREAD

**Issue by evalliETH** [OpenPTrack/open_ptrack_v2#62]
I am trying to perform an intrinsic calibration with a Kinect v2but when I type the command

`sudo ./kinect2_bridge`

an error occurs:

[FATAL] ROS_MASTER_URI is not defined in the environment. Either type the following or (preferrably) add this to your ~/.bashrc file in order set up your local machine as a ROS master:

export ROS_MASTER_URI=http://localhost:11311

then, type 'roscore' in another shell to actually launch the master program.

After doing what it says the error still occurs.
Since in the instructions for intrinsic calibration it is written to ignore the error I proceed with the calibration and, after creating a temporary folder, I type

`roslaunch kinect2_bridge kinect2_bridge.launch`

but another error occur:

arg 'publish_frame' is not defined.

Arg xml is `<arg name="publish_frame" value="$(arg publish_frame)"/>`
The traceback for the exception was written to the log file

I tried to solve it by looking at similar issues from other people but I still don't know how to solve this problem.

**Comment by SimeonOA** [comment]
Hi evalliETH,

Did you modify the .bashrc following the instruction [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Pre-Calibration-File-Configuration#1-modify-the-bashrc)? 

If you are using Docker check at the end of that section for how to edit your .bashrc

Please let me know if this fixes your issue.

Simeon

**Comment by evalliETH** [comment]
Yes, I modified it but the results are always the same.
I think the problem is that I am currently using one computer connected to the Kinect and nothing else, i.e. no master computer. Is it possible to run the system in single-camera mode from a single computer without having to send the data to a master node?

**Comment by SimeonOA** [comment]
Hi evalliETH,

Yes it is possible to run the system in single-camera mode from a single computer. You can use the [single camera container](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images#single_camera_tracking) for this. 

Simeon

**Comment by evalliETH** [comment]
I have modified the .bashrc file as indicated on the error layout but it still doesn't work. When I type

`sudo ./kinect2_bridge`

it always shows the error mentioned above.

**Comment by WenhaoWu00** [comment]
What you could do is to add   <arg name="publish_frame" default="false" /> in your kinect2_bridge.launch file. @evalliETH

**Comment by WenhaoWu00** [comment]
What you could do is to add 
<arg name="publish_frame" default="false" />
in your kinect2_bridge.launch file.

**Comment by Geitenkaas** [comment]
Hello,
I'm having the same issue and cannot locate the kinect2_bridge.launch file. Is it supposed to be inside the docker kinect2_bridge directory?

-Boyd

**Comment by evalliETH** [comment]
> Hello,
> I'm having the same issue and cannot locate the kinect2_bridge.launch file. Is it supposed to be inside the docker kinect2_bridge directory?
> 
> -Boyd

I also can't locate the 'kinect2_bridge.launch' file.

**Comment by c-rizz** [comment]
Hi, you should be able to perform the intrinsic calibration following these instructions: https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration#calibrating-the-kinect-one

**Comment by evalliETH** [comment]
Whenever I run the calibration or the single-camera track the same error occurs:

`Unable to contact my own server at [http://192.168.100.102:34569/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself.  Please check
for errors by running:

ping 192.168.100.102

For more tips, please see

	http://www.ros.org/wiki/ROS/NetworkSetup

The traceback for the exception was written to the log file`

I modified the .bashrc file several times following different suggestions from different sites but it always gives back the same error. Do someone know what causes this?

Eugenio

**Comment by WenhaoWu00** [comment]
kinect2_bridge.launch is located in iai_kinect2/kinect2_bridge/launch folder

**Comment by siehlema** [comment]
I'm having the same Issue here.

It seems to me, that:
`<include file="/root/workspace/ros/src/iai_kinect2/kinect2_bridge/launch/kinect2_frames.launch">
    <arg name="publish_frame" value="$(arg publish_frame)" />
    <arg name="camera" value="$(arg sensor_name)"/>
</include>`
is not working. But even if I insert *publish_frame* and *sensor_name* i get another error, which could be related to this [Issue](https://github.com/code-iai/iai_kinect2/issues/532)

**Comment by siehlema** [comment]
I solved my issue by checking the Problems stated [here](https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting)

In my case I had to add a rules file (90-kinect2.rules into /etc/udev/rules.d) to get the needed access.

**Comment by evalliETH** [comment]
I managed to proceed with the calibration by adding the lines suggested [here](https://github.com/OpenPTrack/open_ptrack_v2/issues/62#issuecomment-491917888) and launching `roscore` in another terminal.
Now the problem is that, when I try recording colored images with 

`rosrun kinect2_calibration kinect2_calibration record color chess4x3x0.1 -color /kinect2_head/mono/image -ir /kinect2_head/ir/image -interval 1 ~/tmp/`

it shows the error:
"_Tried to advertise a service that is already advertised in this node [...]_"

Nothing else appears, that is, no image viewer from which to record images, as stated [here](https://github.com/code-iai/iai_kinect2/issues/250#issuecomment-200753280).

When however I run just

`rosrun kinect2_calibration kinect2_calibration chessx4x3x0.1  record color`

it opens an image viewer, but I also can't record images for later calibration...

Do someone have an idea about how to solve this problem?
Eugenio

**Comment by bearpaw** [comment]
Try to pass values to the arguments:
```
roslaunch kinect2_bridge kinect2_bridge.launch publish_frame:=true sensor_name:=kinect2
```

**Comment by evalliETH** [comment]
When I run the `roslaunch kinect2_bridge kinect2_bridge.launch` or even 'roslaunch kinect2_bridge kinect2_bridge.launch publish_frame:=true sensor_name:=kinect2' command, the terminal  just stops on a line saying

> waiting for clients to connect

Then, on another terminal I run `rosrun kinect2_calibration kinect2_calibration record color chess4x3x0.10 -color /kinect2_head/mono/image -ir /kinect2_head/ir/image -interval 1 ~/tmp/`, as stated on the [intrinsic calibration instructions](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Intrinsic-Calibration) but an error occurs:

> [ERROR] Tried to advertise a service that is already advertised in this node [/kinect2_calib_1562396379489602213/compressed/set_parameters]

I've looked for the meaning of this issue and found people with the same problem [here](https://github.com/code-iai/iai_kinect2/issues/250#issue-142898248). They said it is not important what the error said as long as I click on the image viewer and perform the calibration saving images by pressing "s" or the space-bar. The problem is that no image viewer appears in my case and the terminal on which I've run 'kinect2_bridge.launch' looks like it doesn't detect any client and nothing it's happening, whereas if I launch just `roslaunch kinect2_calibration kinect2_calibration record color chess4x3x0.10`, for instance, an image viewer opens (even though the checkerboard isn't being recognized) and the terminal with 'kinect2_bridge.launch' detects the client. In this case though, even if I can save the Kinect's frames, I can't later use them with the calibration process because the system doesn't recognize the checkerboard (I've tried moving it to different locations with different orientations).

Any idea about this??

Thank you, Eugenio

**Comment by JimZhou-001** [comment]
@evalliETH Hello, have you solved these problems. I meet them, too. And i'm mad of them.

**Comment by evalliETH** [comment]
Hi @JimZhou-001,

Yes, in the end I've managed to calibrate the Kinect following the instruction given [here](https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration), as suggested by @siehlema:

> I solved my issue by checking the Problems stated [here](https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting)
> 
> In my case I had to add a rules file (90-kinect2.rules into /etc/udev/rules.d) to get the needed access.

One thing that I have (luckily) noticed is that when runnig

`rosrun kinect2_calibration kinect2_calibration <chess specifications> record color`

for capturing color images and calibrating the color, the system doesn't immediately detects the checkerboard. At the beginning, as I stated on the question above, I thought that it simply wasn't working, but then I moved the checkerboard around to see if it was detected in other positions and orientations and it was like that indeed (with _detected_ I mean that on the central squares some colored vertical and diagonal lines appear).
In fact, calibrating the color (and later sync: color + IR) is the most boring step because you really have to move around a lot in order to let the system detect the checkerboard.

The IR calibration goes really faster: the checkerboard is detected immediately and in almost every position/orientation.

I hope you could manage to solve your issue!

Cheers,
Eugenio

**Comment by JimZhou-001** [comment]
@evalliETH 
Wow, thank you for your kind reply!

But I'm really new to ROS and Kinect2. Would you mind telling me the detail steps (commond) to calibrate? And after calibration I need to carry out which step of open_ptrack_v2? By the way, which step is extrinsic calibration performed?

So sorry to disturb you. And finally, after you calibrate correctly, do all the errors disappear? I want to run several Kinect2 on one PC. But I don't know how to configure. Can you teach me?

Thank you, my friend.

Yours,
Jim

**Comment by SimeonOA** [comment]
Hi @JimZhou-001 

Step for calibration can be found [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Intrinsic-Calibration)(intrinsic calibration) and [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Camera-Network-Calibration)(extrinsic calibration).

After calibration has been done successfully, you can begin  [person tracking](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Tracking) or [pose annotation](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Pose-Annotation) or [object detection](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Object-Tracking) or [face recognition](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Face-Detection-and-Recognition) depending on your needs. 

Please let us know if you have any other questions.

Simeon

**Comment by bsubbaraman** [comment]
Hi @JimZhou-001 , please try the following steps for intrinsic calibration.  They are adapted from the [link](https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration#calibrating-the-kinect-one) that @c-rizz posted above. 

1. Create a temporary folder for you images: `mkdir ~/tmp`
2. In a terminal, run `roslaunch kinect2_bridge kinect2_bridge.launch publish_frame:=true sensor_name:=kinect2`
3. In a new terminal, capture color images: `rosrun kinect2_calibration kinect2_calibration chess6x5x0.12 record color -path ~/tmp/`, where you should change the values of chess to reflect the dimensions of your checkerboard
4. Hit the space bar to capture a frame.  Move the checkerboard to different positions, angles, and distances from the sensor, ensuring that the checkerboard is correctly detected. The checkerboard is being detected correctly when different colored lines overlay the checkerboard's image. Keep capturing new frames/angles with space bar.
4. Calibrate the intrinsics: `rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 calibrate color -path ~/tmp/`
5. Capture ir images: `rosrun kinect2_calibration kinect2_calibration chess6x5x0.12 record ir -path ~/tmp/`
6.  Repeat step 4 to capture ir frames.
7. Calibrate the intrinsics: `rosrun kinect2_calibration kinect2_calibration chess6x5x0.12 calibrate ir -path ~/tmp/`
8. Capture synchronized images: `rosrun kinect2_calibration kinect2_calibration chess6x5x0.12 record sync -path ~/tmp`
9. Repeat step 4 to capture synchronized frames.  
10. Calibrate the intrinsics: `rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 calibrate sync -path ~/tmp/`
11. Create a folder to save your data:
`roscd kinect2_bridge`
`mkdir -p data/<serial>`
where the serial number is found as is described in step 14 of the intrinsic calibration page.
12. cd into your newly made directory: `cd data/<serial>`
13. Copy the files from your tmp folder into this newly created folder: ` cp ~/tmp/calib_color.yaml ~/tmp/calib_ir.yaml ~/tmp/calib_pose.yaml .`

You can the proceed to your camera network calibration.

**Comment by JimZhou-001** [comment]
@evalliETH @SimeonOA @bsubbaraman 
Hello, friends!

I don't know the result data format. What's the meaning of each row of those .yaml file?

And how can I check whether they are right? Though you provide one method at the bottom of [this link](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Intrinsic-Calibration), I closed those windows and can't run `rosrun rviz rivz` successfully. Do all kinect2 cameras ave similar intrinsics? Do your result similar with mine?

Here are my results:

clib_color.yaml
```
%YAML:1.0
---
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.0436427187093377e+03, 0., 9.4300418248689607e+02, 0.,
       1.0390400114671149e+03, 4.9773900033779444e+02, 0., 0., 1. ]
distortionCoefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 2.0902493835172876e-02, 2.2437270005917952e-02,
       -7.0239145263738152e-03, -1.8679587338700239e-03,
       -4.1527435364637787e-02 ]
rotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
projection: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1.0436427187093377e+03, 0., 9.4300418248689607e+02, 0., 0.,
       1.0390400114671149e+03, 4.9773900033779444e+02, 0., 0., 0., 1.,
       0., 0., 0., 0., 1. ]
```

calib_ir.yaml
```
%YAML:1.0
---
cameraMatrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 3.8003584796682208e+02, 0., 2.5715769737443156e+02, 0.,
       3.7976018447050939e+02, 1.9927494481002762e+02, 0., 0., 1. ]
distortionCoefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ 1.1802262474757745e-01, -2.8157763296348265e-01,
       -4.3541771462468131e-03, -7.0536044675068520e-04,
       5.7074744898090411e-02 ]
rotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
projection: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 3.8003584796682208e+02, 0., 2.5715769737443156e+02, 0., 0.,
       3.7976018447050939e+02, 1.9927494481002762e+02, 0., 0., 0., 1.,
       0., 0., 0., 0., 1. ]
```

calib_pose.yaml
```
%YAML:1.0
---
rotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9993208754498464e-01, -8.2886890518864308e-04,
       1.1624683835148884e-02, 7.7402391266671443e-04,
       9.9998855323342128e-01, 4.7216828685885809e-03,
       -1.1628464426216407e-02, -4.7123644242475730e-03,
       9.9992128312013706e-01 ]
translation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -3.5841255019829550e-02, 3.7946271433135382e-03,
       -5.5389649558108038e-02 ]
essential: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -1.2527734745717322e-06, 5.5371133859765234e-02,
       4.0558608015202171e-03, -5.5802666670013143e-02,
       -1.2298629688781791e-04, 3.5194546544211322e-02,
       -3.8221114293137018e-03, -3.5837699504903571e-02,
       -2.1334238062913774e-04 ]
fundamental: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -3.5943702825459039e-10, 1.5898231528947923e-05,
       -2.7257869309249070e-03, -1.6081434812665600e-05,
       -3.5468408474629990e-08, 7.9970480660493566e-03,
       6.8602234861520782e-03, -2.5713284812603154e-02, 1. ]
```

Thank you very much!

**Comment by jburkeucla** [comment]
Reopening this issue so that we can get the docs updated!

**Comment by SimeonOA** [comment]
Okay. Will update docs.

**Comment by SimeonOA** [comment]
Docs have been updated with alternative instructions  from @bsubbaraman.

**Comment by bsubbaraman** [comment]
Closing again as docs have been updated.
