### ISSUE TITLE
Multi Sensor Pose Annotation - Where is the "Multi View"?

### ISSUE THREAD

**Issue by siehlema** [OpenPTrack/open_ptrack_v2#65]
Hi,

I want to combine the skeletons captured by multiple sensors. I saw in a video on the [OPT 3D Skeleton Tracking Page](http://openptrack.org/overview-3d-skeleton-tracking-pose-recognition-with-opt/) that you combined two skeletons to a "Multi View". I would like to have the same functionality to get more accurate and occlusion free Skeleton Data. But is there an implementation of that in the repo? Unfortunately I couldn't find anything like that.

I would really appreciate if anybody could tell me where I can find this. Alternatively it would be great to know how you did it. Just calculating the mean i guess?

Thank you very much in advance!

Cheers,
Martin

**Comment by jburkeucla** [comment]
﻿Martin,
If you are running multicamera pose tracking the fused data should be available, you just need to pick the appropriate topics in RViz or in your application.   I am not near a running system but we can check for you and let you know.
The fusion approach is discussed in: https://arxiv.org/pdf/1710.06235.pdf
cheers,
Jeff

**Comment by siehlema** [comment]
Hi Jeff,

thank you for your quick response. I'll check that out again, though I think I already tried all available topics. But maybe there is also an issue in my system setup. 

If I'll find some solution, I'll comment again.

**Comment by SimeonOA** [comment]
Hi Martin,

Please use the following topics: 

/tracker/skeleton_markers_arrays
/recognizer/markers 

You can find more information about this [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz#visualizing-pose-recognition-data) and generally about some topics for visualization [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz).

Please let us know if this works for you and if you have any other questions.

Thanks 

Simeon

**Comment by siehlema** [comment]
I think I got it working, but I always have two skeleton arrays on the /tracker/skeleton_markers_arrays topic. Is that normal?

![two skeleton markers](https://user-images.githubusercontent.com/35719687/60028167-24a0df80-969f-11e9-8831-91417ba510f5.png)

**Comment by jburkeucla** [comment]
Yes, by default all skeletons are shown, including both raw and fused- you have to select only the fused/smooth namespace in RViz under the topic – select only the *_valid namespaces under the topic by unchecking the rest:
https://www.dropbox.com/s/rtdgcspo3z1g0l0/image%20%281%29.png?dl=0

I believe the selections will be saved with the RViz configuration but am not sure.

Let us know is this works.

@Simeon, we should document this.

**Comment by siehlema** [comment]
Hi Jeff,

yes that worked! Thank you very much for your help!
Unfortunately I could not find anything about that in the documentation. So maybe you should document this yes.

My question was answered, so I think this issue can be closed :)

**Comment by siehlema** [comment]
There are no more comments on this. So I close this issue.

Thank you for your help

**Comment by JimZhou-001** [comment]
@siehlema Hello!

I want to get skeleton data. But I'm really new to this field. Would you mind telling me how to save and read the result of multi sensor pose annotation in detail? I can only follow [these steps](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Multi-Sensor-Pose-Annotation). But I don't know what to do next.

Thank you.

**Comment by SimeonOA** [comment]
Hi @JimZhou-001 
As stated above, once you are running Multi-sensor pose annotation, the fused data should be available and can be accessed through the following topics: 

/tracker/skeleton_markers_arrays
/recognizer/markers

If you are using RViz, you can find more information about visualizing pose in RVIZ [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz#visualizing-pose-recognition-data).

Please let us know if this works for you.

Thanks 

Simeon
