### ISSUE TITLE
OpenPTrack on Single Computer and Calibration Issues

### ISSUE THREAD

**Issue by evalliETH** [OpenPTrack/open_ptrack_v2#66]
Hi,

Due to limited resources I need to perform skeleton tracking and pose annotation with one single Kinect v2 sensor and one computer only. My question is now, is it possible to use **one single PC** to run both as client node - running sensors drivers and people detection - and master node - for calibration and tracking?

Also, in the case where I could use one single computer for everything, do I have to follow the steps for time synchronization as explained [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Time-Synchronization)?

When I try to start the **intrinsic calibration** following the instruction [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Intrinsic-Calibration) I get the following problems - which I already posted on [this issue](https://github.com/OpenPTrack/open_ptrack_v2/issues/62):

- There is no folder _catkin_; when typing the command `cd/workspace/ros/catkin/devel/lib/kinect2_bridge` or just manually try to access that path I can't find the _catkin_ folder anywhere.
I could find the _kinect2_bridge_ folder, though, but...

- When running `sudo ./kinect2_bridge`, an error occurs telling me that the _ROS_MASTER_URI_ is not defined in the environment. I tried modifying the _~/.bashrc_ page following the instruction [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Pre-Calibration-File-Configuration) but the output is always the same.
I don't understand if it's because I need to have another computer playing as master or because I don't give the computer the right instruction for _reading himself_ and make it run as both master and client.

Finally, when I try to run people tracking or pose annotation without calibration or any other _preparation_ before it, RViz doesn't show me anything and tells me that the fixed frame [map] does not exist.

I'm sorry to bother so much, I am using OpenPTrack for my bachelor thesis which is the first serious project that I have to deal with and I am not very experienced with this stuff.
I hope you could help me with my problems because it is quite some time that I am trying to make this work.

Thank you for your patience,
Cheers,
Eugenio

**Comment by SimeonOA** [comment]
Hi Eugenio,

We are glad to see you are using OpenPTrack.

Please find below some answers to your questions.

If you are using one single camera/sensor, you do not need to do Time Synchronization or Pre-Tracking Calibration or Camera Network Calibration. All those are only required if you are using more than one sensor.

We recommend using the [Docker Images](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images). Specifically after installing Docker, use the instructions [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images#single_camera_tracking) to start a single camera container which is what you need. 

The only thing you need to do when using a single camera is intrinsic calibration. While this is advised, its only purpose is to allow OpenPTrack to correct for any inconsistencies that were introduced during the manufacturing process. We are aware of the issue with Intrinsic calibration and are looking into it.

However, it is possible to at least test your tracking without the intrinsic calibration. 

When you run person tracking/pose annotation without the calibration or any preparation, you should still see tracking on rviz. I would advise the following:
1. Use the preset [rviz configuration](https://github.com/OpenPTrack/open_ptrack_docker_config/blob/master/single_camera_tracking/open_ptrack_config/tracking/conf/SingleCameraTracking.rviz) that comes with the single container. We have already selected some settings that should help you get started. You can then select more topics as you go on and remove those you do not want.  See [here ](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz)for more on visualizing in rviz.
2. If after selecting the preset configuration, you still are not seeing anything, try adjusting your [manual ground plane selection](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Manual-Ground-Plane).

Please let me know if this helps. 

Thanks 
Simeon

**Comment by evalliETH** [comment]
Would using Docker images allow me to manipulate the system and implement algorithms for other purposes, i.e. action recognition?

Anyway I managed to obtain the detection with skeletons tracked by the Kinect and show it on RViz by changing [map] to [world] in the fixed frame.

Thanks for your help!!
Eugenio

**Comment by SimeonOA** [comment]
Hi Eugenio,

Yes you should be able to manipulate the system and implement algorithms while using Docker.

Glad to hear you can visualize detection now. 

Please let me know if you need anything else.

Thanks 
Simeon

**Comment by evalliETH** [comment]
I will try with both systems then and see what performs better.

I am having issues with the calibration as stated [here](https://github.com/OpenPTrack/open_ptrack_v2/issues/62#issuecomment-505417059) but for now I'll just try going on without calibration, hoping it would work anyway.

Thank you for your help!!
Eugenio
