### ISSUE TITLE
Is it possible Object Tracking in a video?

### ISSUE THREAD

**Issue by ablanda** [OpenPTrack/open_ptrack_v2#67]
Hi,
I would like to know if is it possible to give a file video as input setting the configuration?

**Comment by bsubbaraman** [comment]
Hi @ablanda,
Could you clarify what you'd like to do? Running object tracking on a video or live video feed can be done using YOLO (without OpenPTrack), or you can test how well your custom object training did on a pre-recorded video by following [this section](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Training-YOLO#yolo-tracking-settings--testing-on-pre-recorded-video) of the wiki. Please let me know if I've misunderstood the question!

**Comment by jburkeucla** [comment]
Not easily, but you could use the Yolo code directly to achieve this.  https://pjreddie.com/darknet/yolo/
