### ISSUE TITLE
Update ROS GPG key

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#69]
The [Dockerfile for open_ptrack-dev](https://github.com/OpenPTrack/open_ptrack_v2/blob/0b66c79f61be1e3db54e32dc03ee68ab468e7cc4/docker/open_ptrack-dep/Dockerfile#L37) has a GPG key for the ROS repository.

According to [this post](https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454), it is outdated and needs to be updated.

I propose to update this Dockerfile in the master, dev and zed_latest branches. Sound good?

**Comment by SimeonOA** [comment]
Hi,

Thanks.

I would update this ASAP.

**Comment by bsubbaraman** [comment]
Sounds good to me. Thanks!

**Comment by SimeonOA** [comment]
Master, dev and zed_latest branches have been updated.

**Comment by jefft0** [comment]
Thanks, Simeon.
