### ISSUE TITLE
change in the OpenCV distributed with ROS kinetic

### ISSUE THREAD

**Issue by itabr** [OpenPTrack/open_ptrack_v2#7]
During installation of libfreenect2 Cmake fails with following error:
```
make[2]: *** No rule to make target ‘opencv_calib3d-NOTFOUND’, needed by ‘../lib/libfreenect2.so’. Stop.
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
Makefile:127: recipe for target ‘all’ failed
make: *** [all] Error 2
```
This is due to a change in the version of OpenCV distributed with ROS kinetic.

**Comment by marketto89** [comment]
@itabr 

you are right, we are already aware of that change and are looking for the best workaround. 

In the meanwhile, you can temporarily the issue by using one of the solution suggested [here](https://github.com/ros-perception/vision_opencv/issues/193)

**Comment by marketto89** [comment]
This issue should be solved with commit a1df130dbcb04af41b754f35088678b9075507c1

**Comment by dagelabi** [comment]
Hi, I'm trying to install libfreenect2 and I have the same error. I followed the link to the temporary fix, but i'm not sure how to apply it. Can you be a little more specific on how to fix this issue?

Thanks!

**Comment by marketto89** [comment]
@dagelabi 

sorry, I applied the commit only on the OPTv2 repo and not the other ones.
I just pushed another series of commits to the other repos that should fix the issue. Please, remove the libfreenect2 folder and follow the instructions again to download and compile it.
