### ISSUE TITLE
Upgrade supported Linux and ROS versions to 18.04 / melodic

### ISSUE THREAD

**Issue by jburkeucla** [OpenPTrack/open_ptrack_v2#72]
Time to update supported versions...

**Comment by jefft0** [comment]
To minimize the multiple branches, I suggest we first merge the dev branch into master, as Ilya suggested. What do others think?

**Comment by jburkeucla** [comment]
Yes, I would agree this should happen after that step

**Comment by SimeonOA** [comment]
I agree with merging the dev branch into the Master. 

I do not recall any outstanding issues that would prevent this apart from ensuring the suggested fix for (this issue)[https://github.com/OpenPTrack/open_ptrack_v2/issues/70] works across all three imagers. 

Thanks 
Simeon

**Comment by jefft0** [comment]
Which three imagers?

**Comment by jburkeucla** [comment]
Aren’t there different versions of dependencies the two branches?

**Comment by jefft0** [comment]
My understanding was that the dev branch works for Kinect2 and Realsense D435 . Zed integration is still a separate branch with OpenCV versioning issues. That still has to be resolved, but after we merge dev with master. I don't know what is the third imager that Simeon referred to.

**Comment by jefft0** [comment]
I opened issue #73. Please post comments there about merging the dev branch into master. (The current issue is for discussing the upgrade Linux and ROS.)

**Comment by jefft0** [comment]
We currently use CUDA 8.0 and cuDNN 5.1 . But Ubuntu 18.04 requires us to use CUDA 10.0, and this requires the minimum version cuDNN 7.3.1.

Does anyone have experience with CUDA and cuDNN? (I don't.) What problems do you anticipate when upgrading to these newer versions?

**Comment by jefft0** [comment]
https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html

**Comment by MikoyChinese** [comment]
@jefft0 CUDA and cuDNN are just lib, but you need a graphic card support it. And I upgrade this project in Ubuntu18.04 and ros version is melodic. That's ok.

**Comment by bsubbaraman** [comment]
Hi @MikoyChinese ,
Are there any tips that you have for upgrading to Ubuntu 18.04 and ROS melodic?  Were there any parts of the process that were particularly hard that you may be able to let us know about?

Thank you for any information you may be able to provide!

**Comment by jefft0** [comment]
By the way, we have created the branch https://github.com/OpenPTrack/open_ptrack_v2/tree/1804 .

**Comment by jburkeucla** [comment]
Resolved in 1804-dont-build-opencv, will be merged after testing.
