### ISSUE TITLE
Merge dev branch into master

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#73]
As we began discussing on issue #72, the dev branch supports Kinect2 and adds Realsense D435. After merging the fix for issue #70 into the dev branch, we should merge the dev branch into master.

If you know of other changes or tests that need to be made to the dev branch before merging to master, please mention them here.

**Comment by jefft0** [comment]
To repeat from the other issue, my understanding was that the dev branch works for Kinect2 and Realsense D435 . Zed integration is still a separate branch with OpenCV versioning issues. That still has to be resolved, but after we merge dev into master. 

Simeon, you said that we need to make sure that the fix for issue #70 works across all three imagers. Which imagers are those?

**Comment by bsubbaraman** [comment]
I have the same understanding of the current versioning issues, @jefft0 

The dev branch currently works only for single camera; there are a collection of small changes that I've gathered to get it working for multi-camera.  I can commit these modifications this week after I review and test them!

**Comment by SimeonOA** [comment]
Hi,

@jefft0 by three imagers I meant Kinect, Real Sense and Zed.

I misunderstood a previous email from Ilya about the dev branch and thought it had some Zed Integration support. 

I do recall our also discussing that the Zed integration was on a separate branch too.

Sorry about the mix-up.

Simeon

**Comment by jefft0** [comment]
In open_ptrack/Dockerfile, we should change the default branch to master.
https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/docker/open_ptrack/Dockerfile#L4

    ARG branch=master

**Comment by bsubbaraman** [comment]
Good catch - I'll roll this into my next commit.

**Comment by jefft0** [comment]
Also, in open_ptrack_docker_config, the dev branch has dozens of commits since the last commit in master. (I don't know what all those commits are for.)
https://github.com/OpenPTrack/open_ptrack_docker_config/commits/dev

What steps are needed to merge the dev branch into master for open_ptrack_docker_config?

**Comment by bsubbaraman** [comment]
Most of the commits are creating and updating launch files for the RealSense and Zed.  The dev branch of open_ptrack_docker_config currently supports the Kinect, RealSense, and Zed (whereas master supports only Kinect), and so should be used as the master; I'll look into steps needed to merge.

**Comment by jefft0** [comment]
The dev branch has been merged into master. Can we close this issue or is something outstanding?

**Comment by bsubbaraman** [comment]
Thanks for the reminder- closing now.
