### ISSUE TITLE
In Dockerfile, Libfreenect2 section doesn't have ./install_ubuntu.sh

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#74]
In the manual [build instructions for Libfreenect2](https://github.com/OpenPTrack/open_ptrack_v2/wiki/CUDA-and-Other-Softwares-Installation#Libfreenect2), after `apt-get install ...` it has `./install_ubuntu.sh`. But the [Dockerfile](https://github.com/OpenPTrack/open_ptrack_v2/blob/d67cd1f76409788ff779e52d1d528582f85a61a6/docker/open_ptrack-dep/Dockerfile#L121) doesn't have it.

The install_ubuntu.sh file is [here](https://github.com/OpenPTrack/libfreenect2/blob/1606/depends/install_ubuntu.sh). Why doesn't the Dockerfile need it?

(I posted this issue because I'm working on comparing the Dockerfile to the manual build instructions in preparation for supporting Ubuntu 18.04.)

**Comment by itabr** [comment]
Hi just this now, not sure if the script install_ubuntu.sh was needed for the latest version of Libfreenect2 in docker.

**Comment by jefft0** [comment]
I'm closing this issue. Libfreenect2 builds OK in the 1804 branch. I assume we will update the manual build instructions to match. At that point, we can remove the unnecessary `./install_ubuntu.sh` .
