### ISSUE TITLE
Manual install Libfreenect2 section doesn't run setup.bash or set NVCUDASAMPLES_ROOT

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#75]
In the [Dockerfile](https://github.com/OpenPTrack/open_ptrack_v2/blob/d67cd1f76409788ff779e52d1d528582f85a61a6/docker/open_ptrack-dep/Dockerfile#L126), the Libfreenect2 section has the following lines:

    /bin/bash -c "source /opt/ros/kinetic/setup.bash
    export NVCUDASAMPLES_ROOT='/root/workspace/NVIDIA_CUDA-8.0_Samples'

But the [manual build instructions](https://github.com/OpenPTrack/open_ptrack_v2/wiki/CUDA-and-Other-Softwares-Installation#Libfreenect2) for Libfreenect2 doesn't have these.

Why doesn't the manual build need to run setup.bash or set NVCUDASAMPLES_ROOT?

**Comment by itabr** [comment]
I think those lines were accidentally left there after testing, it should have been removed.

**Comment by jefft0** [comment]
OK. I tried building in 16.04 without these lines and it still works. I'll remove them in the Dockerfile for 18.04 (which will become the new master some day soon).  Closing.
