### ISSUE TITLE
There is possibly a mistake in Wiki

### ISSUE THREAD

**Issue by JimZhou-001** [OpenPTrack/open_ptrack_v2#76]
In the following page:
[Intrinsic Calibration](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Intrinsic-Calibration)

There is a line:
`cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge`

But I follow your steps and find it should be like this:
cd ~/workspace/ros/devel/lib/kinect2_bridge

Is it a mistake? Or I build it incorrectly?

**Comment by MikoyChinese** [comment]
Yes, because the path is old. And you should know about the ROS **workspace**, where is workspace is up to you. In the workspace, it offen has 3 folder, build, devel, src. There are some tips about workspace. [[**WORKSPACE**]](http://wiki.ros.org/catkin/workspaces)
