### ISSUE TITLE
Joints Coordinates

### ISSUE THREAD

**Issue by evalliETH** [OpenPTrack/open_ptrack_v2#78]
Hi,

I am having problems by determining the (x, y, z) coordinates of some joints that I need to detect. In particular, when I define the Hand and Elbow joints using opt_msgs (see below), I see that the coordinates are not correct. I could observe that the x-coord is in reality the negative y-coord and that the y-coord is in reality the z-coord. The actual z-coord doesn't correspod to any of the three coordinates that are given.

Here is what I do to obtain the joints' coordinates:

![Screenshot from 2019-07-28 15-41-02](https://user-images.githubusercontent.com/49484349/62007479-2ce0b480-b14e-11e9-911c-159b52f73ce4.png)

Could someone explain me what I do wrong and where the reference frame (origin) for one single Kinect running on single-view is?

I need those information because I am implementing an algorithm to detect a point on a plane that some user is pointing at. The plane is below the kinect and the latter is tilted 30° looking downwards. To determine the point on the plane, I first change coordinate system by rotating everything of 30° on the x-axis and shifting the origin to the lower-left corner of the plane (the image below is a 2D representation of the system, where Kinect and screen are seen sideview):

![Frames](https://user-images.githubusercontent.com/49484349/62007608-e429fb00-b14f-11e9-84c4-e65495ccbc06.jpg)

I think that the reference frame of the Kinect is not where the IR camera is but I can't determine where it actually is and that prevents me from defining the plane correctly.

Thank you,
Eugenio

**Comment by bsubbaraman** [comment]
Hi @evalliETH ,
Try checking the `height` component rather than the `z` component- that should have the information you're looking for.

The joints are being published in the right-handed coordinate system of ROS, where the z-axis is the vertical axis, and the x-y plane is the floor.  If you are working in another coordinate system, you'll have to apply the appropriate transformation; I'm not sure of the particulars of the Kinect's reference frame, but from what you've described, the y-axis is now the vertical axis, with the x-z plane comprising the floor.  It sounds like you know most of the transformation already, so if you can map the `height` component to the correct place, you should be good to go!

**Comment by evalliETH** [comment]
Thanks for your answer @bsubbaraman ,

I've tried calling `.height` instead of `.z` but that variable gives always `0.00`, hence isn't mapped to anything. I have also tried using the `.distance` variable, but that one also didn't have any value.

Any ideas?

Eugenio

**Comment by bsubbaraman** [comment]
Hi @evalliETH ,

After checking on my installation of OPT, the z-coordinate of the joint seems to be properly shown in the the `z` field of `/tracker/skeleton_tracks`.  Are you currently always getting a zero value?

**Comment by evalliETH** [comment]
Hi @bsubbaraman ,

Yes, I also pull the z-coord - and the others - from the topic `/tracker/skeleton_tracks` but those ones are wrong with respect to the Kinect's reference frame, placed on the IR sensor. As stated in the issue, the x-coord - corresponding to the right side of the Kinect, making it face you - is the negative y-coord; the y-coord is actually the z-coord; and and I couldn't find to what the actual z-coord corresponded to.
(Sorry for the bad quality of the image)

![2019-07-30-073246](https://user-images.githubusercontent.com/49484349/62103344-7ccd9180-b29c-11e9-9518-f6c7f74d322f.png)

**Comment by evalliETH** [comment]
Do you know what the OPT (0,0) coordinates are? I am getting crazy trying to manually determine the origin in order to have meaningful and useful coordinates to use on my system.

**Comment by bsubbaraman** [comment]
Ah I see- sorry, I had read your original question to mean that you weren't receiving any z data from OPT.

The joint coordinates should be published in the ROS world frame, so (0,0,0) should be the same as ROS' world origin.  If you're sure about x --> -y and y --> z, then I believe the final mapping should be z --> +/- x, depending on if the Kinect uses a left- or right-handed coordinate system.  If it's not, then my guess is that there's some rotation as well.  You may be able to find more information by looking at the `/tf` topic.

**Comment by evalliETH** [comment]
Hi @bsubbaraman ,

Yeah I guess I was misinterpreting the coordinates. I thought x,y and z came from the sensors's reference frame but in fact they are captured w.r.t. the _world_ ref. frame.
I'll give a look to `/tf` and learn how to perform coordinates transformations and that should be it (I hope).

Thank you and cheers.
Eugenio

**Comment by evalliETH** [comment]
@bsubbaraman, do you know how to use `/tf` on OPT in order to obtain all the coordinates w.r.t. the Kinect's referemce frame?

I've tried to access the `/world` and others reference frames but it looks like they are all placed at the same point, near the ir sensor. But when I look at the coordinates of the hand for example, it looks like the origin is somewhere else. I am getting crazy...

In this picture there are what the system calls `/world` and `/kinect2_head_link` reference frames and they are close to one another and in the same orientation.

![Ref_frames](https://user-images.githubusercontent.com/49484349/62227258-d5e01700-b3bb-11e9-9d27-b66620defa98.png)

**Comment by bsubbaraman** [comment]
Closing as this is more a ROS coordinate system question. Feel free to update with your solution if you solved this!
