### ISSUE TITLE
How can we get 3D body shape like SMPL and SCAPE?

### ISSUE THREAD

**Issue by JimZhou-001** [OpenPTrack/open_ptrack_v2#84]
Hello!

Since pose and shape are often related, I want to get 3D shapes of bodies.

Do you have any idea?

Thank you very much.

**Comment by jburkeucla** [comment]
This is not yet supported (we focus on detection-per-node for scalability rather than fusing image or point cloud data directly0 but is a good idea for future work.

**Comment by MikoyChinese** [comment]
Hi,

You can try this [hmr](https://github.com/akanazawa/hmr) to get the human shape and pose SMPL.

1. Subscribe the camera color data and input it to hmr.
2. Obtain the result from hmr, it will return pose and shape.
3. And transform color image coordinate to depth image, then transform to the world coordinate.
4. Publish mesh to ros message. see this: [ wiki/rviz/DisplayTypes/Marker - Mesh Resource](http://wiki.ros.org/rviz/DisplayTypes/Marker#Mesh_Resource_.28MESH_RESOURCE.3D10.29_.5B1.1.2B-.5D).

**Comment by jburkeucla** [comment]
Thanks, @MikoyChinese for this.  If someone does this, would be happy to review a pull request.
