### ISSUE TITLE
Latest realsense branch?

### ISSUE THREAD

**Issue by msacco22** [OpenPTrack/open_ptrack_v2#89]
Wanted to ask which is the latest branch - compatible with realsense D435 cameras for forking and proposing pull requests? 
Are there any contribution instructions involved?

**Comment by SimeonOA** [comment]
Hi @msacco22 , 

The Master branch should work.

The dev branch which previously contained work on realsense D435 has been merged into Master. So the Master branch should contain what you need 

Work is also ongoing on OpenPTrack for Ubuntu 1804. There is a separate branch for this and it includes support for Realsense as well.

Please let us know if you have any additional questions

Simeon

**Comment by bsubbaraman** [comment]
The 1804 branch (release v2.2) is the latest branch with RealSense support. More info [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Docker-Images#installation)!
