### ISSUE TITLE
'OPTSensorRequest' object has no attribute 'people_detector'

### ISSUE THREAD

**Issue by dagelabi** [OpenPTrack/open_ptrack_v2#9]
Hi,

I'm currently trying to install OpenPTrack, and in the **Camera Network Calibration** when i'm creating the launch files needed for calibration, when I execute : `roslaunch opt_calibration listener.launch`
on both computer. I get this error :

On the slave 
```
[ERROR] [1515102191.871671]: Error processing request: 'OPTSensorRequest' object has no attribute 'people_detector'
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 625, in _handle_request\n
 response = convert_return_to_response(self.handler(request), self.response_class)\n',
'  File "/home/user/workspace/ros/src/open_ptrack/opt_calibration/apps/listener.py", line 357, in handle_create_detector_launch\n    if request.people_detector == OPTSensorRequest.PEOPLE_DETECTOR_YOLO_BASED:\n', "AttributeError: 'OPTSensorRequest' object has no attribute 'people_detector'\n"]
```

On the master : 
```
[ERROR] [1515102191.865713]: Service call failed: service [/suivi/create_detector_launch]
 responded with an error : error processing request: 'OPTSensorRequest' object has no attribute 'people_detector'
```

any ideas ?
Thanks !

**Comment by dagelabi** [comment]
I've changed the line 357 of `ros/src/open_ptrack/opt_calibration/apps/listener.py`
from :
`if request.people_detector == OPTSensorRequest.PEOPLE_DETECTOR_YOLO_BASED:`
to
`if request.people_detector_type == OPTSensorRequest.PEOPLE_DETECTOR_YOLO_BASED:`

and it seems to have worked !

**Comment by marketto89** [comment]
Thank you @dagelabi,

I will push your fix as soon as possible!

Do not hesitate to open other issues should you encounter other problems
