### ISSUE TITLE
People tracking doesn't work but object tracking yes

### ISSUE THREAD

**Issue by yucolabjames** [OpenPTrack/open_ptrack_v2#91]
Continuing from my initial RealSense setup (#90), I noticed there's a problem that is common to the Kinect single camera detection too, that is, people tracking alone doesn't produce any data (Test 1) and; for RealSense having both people tracking + object tracking will consistently create clashes (Test 2 & Test 3).

**Test 1:** pose = false; **people = true**; object = false
```
{
   "header": {
      "seq": 222,
      "stamp": {
         "sec": 1569816955,
         "nsec": 923172104
      },
      "frame_id": "world"
   },
   "people_tracks": [

   ]
}
```

**Test 2:** pose = false; **people = true**; **object = true**
```
{
   "header": {
      "seq": 248,
      "stamp": {
         "sec": 1569817047,
         "nsec": 547360279
      },
      "frame_id": "world"
   },
   "people_tracks": [

   ]
}
```

**Test 3**: pose = false; **people = true**; **object = true**
```
{
   "header": {
      "seq": 849,
      "stamp": {
         "sec": 1569816097,
         "nsec": 244896672
      },
      "frame_id": "world"
   },
   "object_tracks": [
      {
         "id": 2,
         "object_name": "tvmonitor",
         "x": 5.29265,
         "y": -1.58293,
         "height": 0,
         "age": 24.4143,
         "confidence": 0
      },
      {
         "id": 6,
         "object_name": "person",
         "x": 1.80382,
         "y": -0.259634,
         "height": 0,
         "age": 24.4143,
         "confidence": 0
      },
      {
         "id": 9,
         "object_name": "tvmonitor",
         "x": 6.13194,
         "y": 0.146552,
         "height": 0,
         "age": 24.0472,
         "confidence": 0
      },
      {
         "id": 11,
         "object_name": "person",
         "x": 3.21338,
         "y": -1.25142,
         "height": 0,
         "age": 24.0472,
         "confidence": 0
      }, //trimmed
   ]
}
```

**Test 4**: pose = false; people = false; **object = true**
```
{
   "header": {
      "seq": 728,
      "stamp": {
         "sec": 1569817159,
         "nsec": 979002722
      },
      "frame_id": "world"
   },
   "object_tracks": [
      {
         "id": 1,
         "object_name": "tvmonitor",
         "x": 5.88268,
         "y": 0.0834719,
         "height": 0,
         "age": 20.7118,
         "confidence": 0
      },
      {
         "id": 2,
         "object_name": "tvmonitor",
         "x": 3.54613,
         "y": 1.66523,
         "height": 0,
         "age": 20.7118,
         "confidence": 0
      },
      {
         "id": 3,
         "object_name": "tvmonitor",
         "x": 3.68474,
         "y": 1.19501,
         "height": 0,
         "age": 20.7118,
         "confidence": 0
      },
      {
         "id": 5,
         "object_name": "person",
         "x": 4.05234,
         "y": 1.21838,
         "height": 0,
         "age": 20.7118,
         "confidence": 0
      }, //trimmed
   ]
}
```
As you can see in Test 2 and Test 3, both parameters are the same yet sometimes openptrack would return empty array of `people_tracks` and sometimes array of `object_tracks`.

What am trying to get is people track data. It seems rather inefficient to activate object tracking only to keep `person` data only. 

My hardware detail:
Ubuntu 18.04.3 LTS x64
Memory 15.6 GiB
Intel® Core™ i7-7700 CPU @ 3.60GHz × 8
GeForce GT 1030/PCIe/SSE2
Intel RealSense D435

Screenshot of what the camera sees:
![Screenshot from 2019-09-30 12-25-29](https://user-images.githubusercontent.com/40826198/65849508-7089b180-e37d-11e9-99f1-5d53dca39412.png)

**Comment by bsubbaraman** [comment]
I'm glad you got things running!  It is expected that the person tracks will be empty when there are no detections.  Do you see detections when you walk around in the space?  From your photo, only your head is visible; for people tracking, your whole body should be in the imager's view, ideally in an open space.  

The object tracks will also have people, since the default weights used by YOLO are trained on people as well.  These are distinct from OpenPTrack's person tracks.  If your use case requires incomplete views of a person's body (like in your provided photo), using YOLO's 'person' object's may be a better approach.

**Comment by yucolabjames** [comment]
Alright so the team was kind enough to clear a large chunk of our storeroom for me to use. Can see the whole body now. I believe I identified the problem, but not too sure how to solve it. Rviz is now complaining about this:

```
Global Status: Error
Fixed Frame [world] does not exist

TF
Status: Warn
No transform from realsense_head_aligned_depth_to_color...
No transform from realsense_head_aligned_depth_to_infra...
No transform from realsense_head_color_frame
No transform from realsense_head_color_optical_frame
No transform from realsense_head_depth_frame
No transform from realsense_head_depth_optical_frame
No transform from realsense_head_infra1_frame
No transform from realsense_head_infra1_optical_frame
No transform from realsense_head_infra2_frame
No transform from realsense_head_infra2_optical_frame
No transform from realsense_head_link
```

![bigger space](https://user-images.githubusercontent.com/40826198/66038163-e8a1d400-e543-11e9-9a94-63a755cc2a1a.PNG)

![world error](https://user-images.githubusercontent.com/40826198/66038126-d0ca5000-e543-11e9-975a-0a38cdf1a255.PNG)

**Comment by SimeonOA** [comment]
Hi @yucolabjames, 

In Rviz, under 'Global Options' change your 'Fixed Frame' from 'World'. 

This should solve your issue.

More information on using Rviz is [here](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Visualizing-OPT-Data-in-RViz)

**Comment by yucolabjames** [comment]
Hello @SimeonOA,

Thanks for looking into this issue. It seems changing ‘Fixed Frame’ to other values create other complications, been toggling different values in rviz with little result, the UDP message still returns empty array for person tracking.



![E3D525C6-FD14-4639-BF3B-2B6CC0B57F64](https://user-images.githubusercontent.com/40826198/66173483-f4e07b00-e682-11e9-8b82-ad394a274d34.jpeg)

**Comment by bsubbaraman** [comment]
Do you get a pop-up window asking to pick 3 points on the floor after launching the tracking node?  Or are any errors printed in the terminal window after running the launch command?

**Comment by cmdrogogov** [comment]
I am expriencing a similar issue with UDP packets - openPtrack doesn't seem to be publishing data in a format the OM_CHOP components in the TD branch can understand.  

I am not, however, recieving any errors in Rviz at this time.

 yucolabjames - did you ever find a workaround to this, and if so what was it?
