### ISSUE TITLE
Broken images on open_ptrack_v2 wiki and suggested fix

### ISSUE THREAD

**Issue by etjones** [OpenPTrack/open_ptrack_v2#94]
Hi - A number of images on the [open_ptrack_v2 wiki](https://github.com/OpenPTrack/open_ptrack_v2/wiki) don't appear when for me when I load the page; looks like they weren't updated when the `images` directory was moved from `docker/images` to  the top-level `images`.   Here's [one example page](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Manual-Ground-Plane)

Since there's [no easy way](https://stackoverflow.com/a/11481887) to make pull requests for a Github wiki, here's a suggested fix:

In the wiki repo, a global search-and replace from:

`https://github.com/OpenPTrack/open_ptrack_v2/blob/docker/images/`

to :

`https://raw.githubusercontent.com/OpenPTrack/open_ptrack_v2/master/images/`

makes those images appear for me.

**Comment by SimeonOA** [comment]
Hi

Thank you for pointing this out.

We would work on this and ensure the images are correctly loaded.

Regards,
Simeon
