### ISSUE TITLE
Kinectv2 not found

### ISSUE THREAD

**Issue by muella91** [OpenPTrack/open_ptrack_v2#96]
Hello,

First, I already checked all the other issues, nothing of that helped for me.

So am booting an Ubuntu 16.04 from a USB-Stick. I installed OPT via docker, installation without any problems. If I run single camera person tracking, the system does not recognize my Kinect v2, the status LED at the Kinect is off. I get an error that the Kinect v2 is not found, I dont see any picture at RVIZ.

I already tried all suggestions from the "Troubleshooting - Kinect Cannot Be Found". Nothing helped.

I tried out Protonect (https://github.com/OpenKinect/libfreenect2) - here my Kinect v2 works without any problems.

Any suggestions what else I could try?
Thanks

**Comment by bsubbaraman** [comment]
Hi @muella91,
2 initial things to try if you haven't already, just to cover all bases: If you're running inside docker, you can try exiting the docker container, stop the container by running `./run_single_camera -s`, and then try running again. If this doesn't work, try restarting the computer with the kinect plugged in.

Can you post the error that is being printed?

**Comment by bsubbaraman** [comment]
Were you able to resolve your problem, @muella91?

**Comment by muella91** [comment]
> Were you able to resolve your problem, @muella91?

Sorry, I totally forgot to answer. First, thanks for your quick reply!
Rebooting the computer helped, I guessed before I only tried to restart the container.

**Comment by bsubbaraman** [comment]
Great - please let us know if you have any other questions/issues!
