### ISSUE TITLE
Remove unneeded ground_based_people_detector_node_zed.cpp?

### ISSUE THREAD

**Issue by jefft0** [OpenPTrack/open_ptrack_v2#97]
In the 1804 branch, we updated ground_based_people_detector_node_zed.cpp to check for `sensor_type == "zed"` and do the proper initialization. So, we can remove https://github.com/OpenPTrack/open_ptrack_v2/blob/1804/detection/apps/ground_based_people_detector_node_zed.cpp . Right?

**Comment by bsubbaraman** [comment]
You're right - I'll test just to make sure, and incorporate into my next commit.

**Comment by bsubbaraman** [comment]
Done here 0252f6417d3114bcba79ece78018f4f69dcafcba (with corresponding changes to CMakeLists.txt in the subsequent commit)
